version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ai_qa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-gateway:
    image: ${NAMESPACE}/api-gateway:${TAG:-latest}
    container_name: api-gateway
    restart: unless-stopped
    depends_on:
      - qa-service
      - user-service
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  qa-service:
    image: ${NAMESPACE}/qa-service:${TAG:-latest}
    container_name: qa-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_qa?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  user-service:
    image: ${NAMESPACE}/user-service:${TAG:-latest}
    container_name: user-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_qa?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  qa-frontend:
    image: ${NAMESPACE}/qa-frontend:${TAG:-latest}
    container_name: qa-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  mysql_data: