server:
  port: 8082
spring:
  application:
    name: qa-service
  cloud:
    nacos:
      discovery:
        server-addr: 54.219.180.170:8848
      config:
        server-addr: 54.219.180.170:8848
        file-extension: yml # 指定配置文件格式