server:
  port: 8081
spring:
  application:
    name: user-service-cdw
  cloud:
    nacos:
      server-addr: 54.219.180.170:8848
  datasource:
    url: jdbc:mysql://localhost:3306/ai_qa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #datasource:
    #url: jdbc:mysql://54.219.180.170:3306/ai_qa_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #username: root
    #password: ai_qa_system
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

jwt:
  secret: R7E8a3rXn8m9Yq0sT5v2u6w1z0A8B4cD
  expiration:
    ms: 86400000

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    org.apache.coyote.http11: debug