name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Export variables
      run: |
        echo "NAMESPACE=myrepo" >> $GITHUB_ENV
        echo "TAG=${{ github.sha }}" >> $GITHUB_ENV   # 或固定版本号

    - name: Build backend services
      run: |
        cd backend-services/api-gateway && mvn clean package -DskipTests
        cd ../qa-service     && mvn clean package -DskipTests
        cd ../user-service   && mvn clean package -DskipTests

    - name: Build frontend
      run: |
        cd qa-frontend
        npm ci
        npm run build
    - name: DEBUG – 把密钥写成文件
      run: |
        echo '${{ secrets.EC2_SSH_KEY }}' > /tmp/debug_key
        echo '${{ secrets.EC2_HOST }}' > /tmp/debug_host
        echo '${{ secrets.EC2_USER }}' > /tmp/debug_user

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!node_modules,.git"
        target: ~/ai-qa-system

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/ai-qa-system
          docker compose down
          docker compose up -d --build
  
