name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build backend services
      run: |
        cd backend-services/api-gateway && mvn clean package -DskipTests
        cd ../qa-service     && mvn clean package -DskipTests
        cd ../user-service   && mvn clean package -DskipTests

    - name: Build frontend
      run: |
        cd qa-frontend
        npm ci
        npm run build

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: ".,!node_modules,.git"
        target: ~/ai-qa-system

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/ai-qa-system
          docker compose down
          docker compose up -d --build
